language: cpp
compiler: gcc
sudo: required
dist: bionic

addons:
  apt:
    packages:
      - p7zip-full
      - python3-pip
      - python3-setuptools
matrix:
  include:
  - name: "Linux x86_64"
    os: linux
    install:
      - sudo pip3 install requests semantic_version lxml
      - ls
      - sudo ./qt-downloader
    script:
      - g++ test.cpp
      - ls     
