language: cpp
compiler: gcc
sudo: required
dist: bionic

addons:
  apt:
    packages:
      - p7zip-full
      - python3-pip
      - python3-setuptools

env:
  global:
    - QT_VERSION=5.14.1
    - QT_INSTALL_DIR=~/Qt

matrix:
  include:
  - name: "Linux x86_64"
    os: linux
    install:
      - sudo pip3 install requests semantic_version lxml
      - ls
      - sudo python3 ./qt-downloader linux desktop ${QT_VERSION} gcc_64 --output=${QT_INSTALL_DIR}
    script:
      - g++ test.cpp
      - sudo ls ${QT_INSTALL_DIR}/${QT_VERSION}/gcc_64 
