language: cpp
compiler: gcc
sudo: required
dist: bionic

addons:
  apt:
    packages:
      - p7zip-full
      - python3-pip
      - python3-setuptools
matrix:
  include:
  - name: "Linux x86_64"
    os: linux
    script:
      - g++ test_build.cpp
      
